In [1]:
import torch
import numpy as np

In [2]:
#1
#Tensors can be created directly from data. The data type is automatically inferred.
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
#2
#Tensors can be created from NumPy arrays:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
#3
#From another tensor:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [5]:
#4
tensor = torch.ones(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
#5
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
#6
triple_tensor = torch.cat([tensor, tensor, tensor], dim=1)
print(triple_tensor)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [8]:
#7
tensor = torch.ones(4, 4)
tensor[:,1] = 0
y1 = tensor @ tensor.T
y2 = tensor * tensor.T
print(y1)
print(y2)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
#8
y3 = torch.rand_like(y1)
print(y3)
agg = y3.sum()
print(agg)

tensor([[0.0147, 0.9204, 0.8331, 0.0350],
        [0.2067, 0.7151, 0.7642, 0.8414],
        [0.6230, 0.1597, 0.5664, 0.4120],
        [0.6489, 0.7899, 0.0805, 0.7171]])
tensor(8.3281)


In [10]:
#9
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [11]:
#10
# A change in the tensor reflects in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [12]:
#11
n = np.ones(5)
t = torch.from_numpy(n)
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [16]:
#12
from torch import nn

device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using mps device


In [17]:
#13
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [18]:
#14
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='mps:0')


In [19]:
#15
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [20]:
#16
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [21]:
#17
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [22]:
#18
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.3046, -0.4486, -0.1809,  0.1230,  0.1369, -0.0377,  0.1845,  0.4336,
         -0.1245,  0.1174, -0.6741,  0.0480,  0.0981,  0.3365,  0.4362,  0.3127,
         -0.3651, -0.0770, -0.0150, -0.0411],
        [ 0.4933, -0.6640, -0.5060,  0.3989,  0.1486,  0.0193, -0.1941,  0.6522,
         -0.2349,  0.4192, -0.5171,  0.0982, -0.4726,  0.0799, -0.1263,  0.1813,
         -0.1692, -0.1220, -0.1225, -0.4148],
        [ 0.4813, -0.7012, -0.3397, -0.0579, -0.2096, -0.2108,  0.0297,  0.3630,
         -0.2395,  0.3546, -0.6797, -0.2255, -0.2869, -0.1882, -0.2854,  0.0711,
         -0.1620, -0.2179, -0.0999,  0.3146]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.3046, 0.0000, 0.0000, 0.1230, 0.1369, 0.0000, 0.1845, 0.4336, 0.0000,
         0.1174, 0.0000, 0.0480, 0.0981, 0.3365, 0.4362, 0.3127, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.4933, 0.0000, 0.0000, 0.3989, 0.1486, 0.0193, 0.0000, 0.6522, 0.0000,
         0.4192, 0.0000, 0.0982, 0.0000, 0.0799, 0.00

In [23]:
#19
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)

In [24]:
#20
softmax = nn.Softmax(dim=1)
pred_probs = softmax(logits)
pred_probs

tensor([[0.0704, 0.1049, 0.0792, 0.0917, 0.0899, 0.1059, 0.1400, 0.1193, 0.1089,
         0.0899],
        [0.0753, 0.1033, 0.0870, 0.0915, 0.0946, 0.1152, 0.1268, 0.1175, 0.1052,
         0.0835],
        [0.0738, 0.0972, 0.0789, 0.1031, 0.1020, 0.1120, 0.1307, 0.0960, 0.1177,
         0.0886]], grad_fn=<SoftmaxBackward0>)

In [25]:
#21
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0006,  0.0017,  0.0164,  ..., -0.0045, -0.0242, -0.0203],
        [ 0.0253, -0.0285,  0.0142,  ..., -0.0229, -0.0180, -0.0128]],
       device='mps:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([ 0.0063, -0.0142], device='mps:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0417,  0.0115, -0.0004,  ..., -0.0236, -0.0162, -0.0041],
        [-0.0014, -0.0404, -0.0102,  ..., -0.0031,  0.0413, -0.0047]],
       device='mps:0', grad_fn=<Slice